### ISSUE TITLE
Misleading code at the end of the "Using Roles" section

### ISSUE THREAD

**Issue by kjleitz** [learn-co-curriculum/devise_roles_readme#12]
At the end of the "USING ROLES" subsection of this README, these examples are given:

> Another technique is to use ActiveSupport's `try` whenever we're using an object that might be `nil`:
> 
> ```
> if current_user.try(:admin?)
>   # current user is not nil and is an admin
> else
>   # current user is nil or has a role that is not admin
> end
> ```
> 
> This is perhaps cleaner, since it delegates the bizarre re-opening of `NilClass` to `ActiveSupport#try`, but it is a little bit less readable than this:
> 
> ```
> if current_user.admin?
>   # current user is not nil and is an admin
> else
>   # current user is nil or has a role that is not admin
> end
> ```
> 
> So use your discretion.

But it implies that those two code blocks will do the same thing, which isn't true! Using `current_user.try(:admin?)` will either return the value of `current_user.admin?` if it responds to that method, or `nil` if it doesn't, meaning that the `else` clause can be executed if `current_user` is `nil`. Using `current_user.admin?` will either return the value of `current_user.admin?` if it responds to that method, or it will **throw an error** if it doesn't, meaning that the `else` clause will **never** be executed if `current_user` is `nil`. The comment inside the latter `else` block is wrong; it will not be executed if "`current user is nil...`".

I think that's a big distinction to make! That's why `try` is so useful :)

**Comment by gj** [comment]
Good catch @kjleitz !

We're currently in the process of tweaking the authentication and authorization section, and this is great feedback.

**Comment by sgharms** [comment]
Better later than never! Caught, updated, fixed, and shipped.
